#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "› brew bundle"
  brew bundle
fi
# find the installers and run them iteratively
find . -name install.sh -not -path "*oh_my_zsh*" | while read installer ; do sh -c "${installer}" ; done
